on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://jamieg.sgedu.site/jamieg.sgedu.site/public_html/wordpress/
        ftp-username: ftp@jamieg.sgedu.site
        ftp-password: bewdCMS1
